export const data = {
    products: [
        {
            name: 'Free Shirt',
            slug: 'free-shirt',
            category: 'Shirts',
            image:'/images/shirt1.jpg',
            price:'70',
            brand:'nike',
            rating: 4.5,
            numReviews: 8,
            countInStock: 5,
            description: 'A popular shirt',

        },
        {
            name: 'Fit Shirt',
            slug: 'fit-shirt',
            category: 'Shirts',
            image:'/images/shirt2.jpg',
            price:'80',
            brand:'addidas',
            rating: 3.2,
            numReviews: 10,
            countInStock: 20,
            description: 'A popular shirt',

        },
        {
            name: 'Slim Shirt',
            slug: 'slim-shirt',
            category: 'Shirts',
            image:'/images/shirt3.jpg',
            price:'90',
            brand:'Raymond',
            rating: 4.5,
            numReviews: 3,
            countInStock: 20,
            description: 'A popular shirt',

        },
        {
            name: 'Golf pant',
            slug: 'Golf-pant',
            category: 'Pants',
            image:'/images/pants1.jpg',
            price:'90',
            brand:'Oliver',
            rating: 2.9,
            numReviews: 13,
            countInStock: 20,
            description: 'Smart looking pants',

        },
        {
            name: 'Golf pant',
            slug: 'Golf-pant2',
            category: 'Pants',
            image:'/images/pants2.jpg',
            price:'90',
            brand:'Oliver',
            rating: 2.9,
            numReviews: 13,
            countInStock: 20,
            description: 'Smart looking pants',

        },
        {
            name: 'Golf pant',
            slug: 'Golf-pant3',
            category: 'Pants',
            image:'/images/pants3.jpg',
            price:'90',
            brand:'Oliver',
            rating: 2.9,
            numReviews: 13,
            countInStock: 20,
            description: 'Smart looking pants',

        },
    ],
}